name: mercatos
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  auto_route: null
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.5.3+2
  flutter_smart_dialog: ^4.5.3+2
  flutter_svg: ^1.1.1
  formz: ^0.4.1
  google_fonts: ^3.0.1
  http_parser: ^4.0.1
  hydrated_bloc: ^8.1.0
  loading_animation_widget: ^1.2.0+2
  modal_bottom_sheet: ^2.1.0
  path_provider: ^2.0.11
  scrollable_positioned_list: ^0.3.2
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.4
  video_player: ^2.4.5

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
