name: mercatos
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.0.3
  chewie: ^1.3.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.5.3+2
  flutter_smart_dialog: ^4.5.3+2
  formz: ^0.4.1
  http_parser: ^4.0.1
  hydrated_bloc: ^8.1.0
  loading_animation_widget: ^1.2.0+2
  path_provider: ^2.0.11
  pedantic: ^1.11.1
  video_player: ^2.4.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
